version: "3.6"
services:
  #Gitlab Container
  gitlab:
    image: gitlab/gitlab-ce:16.9.8-ce.0
    container_name: gitlab
    restart: always
    hostname: "gitlab-template.com.br"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-template.com.br:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - "8929:8929"
      - "443:443"
      - "2424:2424"
    volumes:
      - "./core/config:/etc/gitlab"
      - "./core/logs:/var/log/gitlab"
      - "./core/data:/var/opt/gitlab"
    shm_size: "256m"
